feat: Bluetooth

diff --git a/eggs/scripts/smb-manager b/eggs/scripts/smb-manager
--- a/eggs/scripts/smb-manager
+++ b/eggs/scripts/smb-manager
@@ -12,7 +12,7 @@ CONFIG="/etc/smb/hosts.json"
 
 # Helper functions
 err() {
-    echo "Error - $1"
+    echo "Error - $1" 1>&2
     exit 1
 }
 
