rework: Mark X11 only scripts

diff --git a/src/.local/bin/X11-sxkill b/src/.local/bin/X11-sxkill
--- a/src/.local/bin/X11-sxkill
+++ b/src/.local/bin/X11-sxkill
@@ -3,6 +3,11 @@
 # Kill window by selection
 #  This will forcefully kill the process
 
+! xhost >& /dev/null && {
+    echo "Invalid X11 session!"
+    exit 1
+}
+
 if [[ -z $(pgrep -f "^xdotool selectwindow windowkill$") ]];
     then xdotool selectwindow windowkill &
     else pkill -f "^xdotool selectwindow windowkill$";
